### ISSUE TITLE
Camera rotation on mobile?

### ISSUE THREAD

**Issue by ivodopiviz** [nyatla/NyARToolkitUnity#1]
Hi, it seems like NyARToolkit doesn't take into account WebCamTexture.videoRotationAngle nor WebCamTexture.videoVerticallyMirrored, so when used on some Android devices, the video always appears rotated, regardless of the actual device orientation.

The easiest way to fix this is to rotate the geometry you're using the texture on and maybe using the UV coords to fix flipping.

Is this supported? If not, could you give me some pointers on how to add it?

Thanks!

**Comment by nyatla** [comment]
Hi,

I'm sorry for slow reply.
I had never used NyARToolkit on Android device.

> The easiest way to fix this is to rotate the geometry you're using the texture on and maybe using the UV coords to fix flipping.

This sounds good.

You can flip the captured image with the following code.
If you switch this by flag, does it go well?
![default](https://cloud.githubusercontent.com/assets/2483108/17428963/fc3c671e-5b26-11e6-9708-681ea5b873c9.png)

Please let me know if you went well.

**Comment by ivodopiviz** [comment]
Surprisingly, no. Setting any scale to -1 makes the display to draw random colors / garbage. I tested on PC and an Android device with the same result. I tried with the "Standard" base shader and the "Unlit / Texture" one but neither worked.

No UV flipped:
![no_flip](https://cloud.githubusercontent.com/assets/250464/17444328/c119c8e0-5b15-11e6-87a2-34bb8fe27b68.png)

Just one flipped:
![x_flipped](https://cloud.githubusercontent.com/assets/250464/17444335/c982afb0-5b15-11e6-88f1-d1e46f7f8e5a.png)

Both flipped:
![xy_flipped](https://cloud.githubusercontent.com/assets/250464/17444339/cec2ab4c-5b15-11e6-9bc5-233f949e5dce.png)

**Comment by nyatla** [comment]
Thank you for screen shot.
I was a little misunderstood the problem.

You might get solution by rotate the camera.

let to set camera rotation parameter.Z to 180.
This will be upside down.

![1](https://cloud.githubusercontent.com/assets/2483108/17461171/83f10d94-5cbd-11e6-865b-56c1baa311da.png)
